#!/usr/bin/env python3
"""Build the per-(corpus, language) pnc_text / text_field / num_tokens table
in docs/pnc_coverage.md.

Combines two sources, since re-scanning the whole 99.8M-cut collection every
time this table needs refreshing is not worth it:

* the exhaustive baseline audit from 2026-08-11
  (``/mnt/scratch-nyx/giuseppe/melt/shar-audit/shar_audit_2026-08-11.csv``,
  MELT-proj/preprocessing's ``verification/check_shar_content.py`` on branch
  ``feat/shar-leaf-auditor``), for corpora untouched since;
* a fresh re-audit of ``mls_sidon``, ``fleurs``, ``voxpopuli`` from
  2026-08-12, run with ``--text-field custom.pnc_text --tokens`` so
  ``num_tokens`` is checked against the field these corpora actually train
  on, not the plain-text default -- checking it against the wrong field
  makes every cut that has pnc_text look like a "mismatch", which it is not.

Re-run the audit yourself before trusting this beyond the corpora it already
covers:

    singularity exec --bind /mnt/scratch-nyx,/mnt/scratch-artemis \\
      /mnt/scratch-artemis/giuseppe/melt-data/melt_cuda126_lhotse2_td.sif \\
      bash -c 'source /workspace/venv/bin/activate
        export HF_HOME=/mnt/scratch-artemis/giuseppe/.cache/huggingface
        export HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1
        python3 verification/check_shar_content.py \\
          /mnt/scratch-nyx/giuseppe/melt/melt-data/shar/<corpus> \\
          --text-field <its recommended field, from this table> \\
          --jobs 8 --tokens --csv OUT.csv'

then add an entry to FRESH below and regenerate.

Usage: python3 infra/build_pnc_coverage_table.py > docs/pnc_coverage.md
"""
import csv
import sys
from collections import defaultdict
from pathlib import Path

AUDIT_ROOT = Path("/mnt/scratch-nyx/giuseppe/melt/shar-audit")
BASELINE = AUDIT_ROOT / "shar_audit_2026-08-11.csv"

# Corpora with a fresher, correctly-scoped audit than the baseline above.
FRESH = {
    "mls_sidon": AUDIT_ROOT / "2026-08-12/mls_sidon.csv",
    "fleurs": AUDIT_ROOT / "2026-08-12/fleurs.csv",
    "voxpopuli": AUDIT_ROOT / "2026-08-12/voxpopuli.csv",
}
TOKENIZER_VERIFIED = {"mls_sidon", "fleurs", "voxpopuli"}  # the FRESH set, by definition

# Where each corpus keeps the text the campaign should train on. Corpora
# whose canonical field is custom.pnc_text fall back to plain supervision
# text per leaf, until that leaf's own pnc_text coverage says otherwise --
# see the per-row logic below.
CORPUS_FIELD = {
    "cv22_sidon": "custom.metadata.sentence",
    "mls_sidon": "custom.pnc_text",
    "fleurs": "custom.pnc_text",
    "voxpopuli": "custom.pnc_text",
    "covost2": "text (supervision)",
    "yodas-granary": "text (supervision)",
    "librispeech": "custom.pnc_text",
    "peoples_speech": "custom.pnc_text",
}

PREAMBLE = """\
# pnc_text / text_field / num_tokens coverage, by corpus and language

Generated by `infra/build_pnc_coverage_table.py` — do not hand-edit. See that
script's docstring for exactly which audit each row's numbers come from and
how to refresh it.

Columns:

* **pnc_text** — % of cuts (weighted across that language's splits) carrying
  a non-empty `custom.pnc_text`.
* **recommended text_field** — what a config's `text_field` tag should be set
  to for this corpus/language today. `MIXED` means some leaves (usually one
  split) have `pnc_text` and others don't — do not point a source at
  `custom.pnc_text` in this state without checking which split you mean;
  `data.strict_text_field: true` will fail loudly on the ones that don't.
  `-- pending PNC` means no leaf for this language has it yet.
* **num_tokens** — % of cuts carrying `custom.num_tokens`, counted against the
  *recommended* field, not blindly against supervision text.
* **tokenizer** — `Qwen/Qwen3-1.7B` is the whole collection's convention.
  Only `mls_sidon`, `fleurs`, and `voxpopuli` have had a fresh
  recompute-and-compare run against it (2026-08-12, zero mismatches found).
  Everywhere else, "assumed" means the value is trusted from whenever it was
  written, not re-verified in this pass — see `history/17-data-consistency-plan.md`
  §5's "recompute, do not trust" principle before relying on it for a new use.

"""


def leaf_lang(corpus: str, leaf: str) -> str:
    """First path component after the corpus prefix, if any.

    Baseline rows carry the corpus in the leaf path ("mls_sidon/dutch/dev");
    the FRESH per-corpus audits were rooted at the corpus dir, so their leaf
    paths omit it ("dutch/dev"). Strip the prefix if present either way.
    """
    parts = leaf.split("/")
    if parts and parts[0] == corpus:
        parts = parts[1:]
    return parts[0] if parts else leaf


def load_csv(path: Path) -> list[dict]:
    with open(path) as f:
        return list(csv.DictReader(f))


def main() -> None:
    by_corpus_lang: dict[tuple[str, str], list[dict]] = defaultdict(list)

    for r in load_csv(BASELINE):
        corpus = r["corpus"]
        if corpus not in CORPUS_FIELD or corpus in FRESH:
            continue  # not tracked, or superseded by a fresher audit below
        if int(r["cuts"]) == 0:
            continue  # empty leaf, e.g. mls_sidon_v2
        by_corpus_lang[(corpus, leaf_lang(corpus, r["leaf"]))].append(r)

    for corpus, path in FRESH.items():
        if not path.exists():
            print(f"WARNING: {path} missing, skipping {corpus}", file=sys.stderr)
            continue
        for r in load_csv(path):
            if int(r["cuts"]) == 0:
                continue  # empty leaf, e.g. fleurs/ur_pk/train
            by_corpus_lang[(corpus, leaf_lang(corpus, r["leaf"]))].append(r)

    out = [PREAMBLE.rstrip("\n")]
    out.append("| corpus | language | cuts | pnc_text | recommended text_field | num_tokens | tokenizer |")
    out.append("|---|---|---:|---:|---|---:|---|")

    for (corpus, lang), leaves in sorted(by_corpus_lang.items()):
        total_cuts = sum(int(r["cuts"]) for r in leaves)
        if total_cuts == 0:
            continue
        pnc_pct = sum(int(r["cuts"]) * float(r["pct_pnc_text"]) for r in leaves) / total_cuts / 100 * 100
        tok_pct = sum(int(r["cuts"]) * float(r["pct_num_tokens"]) for r in leaves) / total_cuts / 100 * 100

        base_field = CORPUS_FIELD[corpus]
        if base_field == "custom.pnc_text":
            if pnc_pct >= 99.9:
                field = "custom.pnc_text"
            elif pnc_pct <= 0.1:
                field = "text (supervision) -- pending PNC"
            else:
                field = f"MIXED ({pnc_pct:.0f}% pnc_text) -- do not use directly"
        else:
            field = base_field

        if tok_pct <= 0.1:
            tok_note = "-"
        else:
            tok_note = "Qwen/Qwen3-1.7B" + (
                " (reverified 2026-08-12)" if corpus in TOKENIZER_VERIFIED
                else " (assumed, not reverified)"
            )

        out.append(
            f"| {corpus} | {lang} | {total_cuts:,} | {pnc_pct:.1f}% | {field} | "
            f"{tok_pct:.1f}% | {tok_note} |"
        )

    print("\n".join(out))


if __name__ == "__main__":
    main()
